x-redash-service: &redash-service
  image: redash/redash:8.0.0.b32245
  depends_on:
    - postgres
    - redis
  env_file: ./.env
  restart: unless-stopped
  networks:
    - net

x-infra-service: &infra-service
  restart: unless-stopped
  networks:
    - net

services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 1
    networks:
      - net
  
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  
  redis:
    <<: *infra-service
    image: redis:6.2-alpine
  
  postgres:
    <<: *infra-service
    image: postgres:14-alpine
    env_file: ./.env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./:/app
    working_dir: /app
    ports:
      - "5432:5432"

volumes:
  postgres:
  redash:

networks:
  net:
    driver: bridge
